### ISSUE TITLE
SubClassOf axiom rendering in justification list is missing ":" 

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/explanation-workbench#10]
SubPropertyOf axioms have a colon, but not SubClassOf.

<img width="329" alt="screen shot 2017-04-27 at 11 07 02" src="https://cloud.githubusercontent.com/assets/4361140/25490044/b268d472-2b39-11e7-97b8-021e8d388e35.png">

**Comment by ykazakov** [comment]
This probably related to the OWL API issue owlcs/owlapi#534

**Comment by ykazakov** [comment]
According to the [specs of the Manchester syntax](https://www.w3.org/TR/owl2-manchester-syntax/) all axiom keywords should be rendered with a colon.

**Comment by matthewhorridge** [comment]
In the case of justifications I prefer the rendering without the colon :)  

The official Manchester syntax doesn't support rendering axioms like this anyway, so I would say that some "poetic license" is acceptable in this case.  Personally, I'd prefer to get rid of the colon from SubPropertyOf.

**Comment by matthewhorridge** [comment]
Fixed so colon is not rendered after SubPropertyOf
